/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2019-11-06
*/
#include "stm32f4xx.h"
#include "FreeRTOS.h"
#include "task.h"
#include "GPIODriver.h"
#include "queue.h"
#include "semphr.h"


//Greed Led
#define LedGreen_port	    PORTD
#define	LedGreen_pin		PIN12
GPIOcfgType LedGreen;
//Red diode
#define DiodeRed_port       PORTD
#define DiodeRed_pin        PIN14
GPIOcfgType DiodeRed;

#define Button_port         PORTA
#define Button_pin          PIN0
GPIOcfgType Button;


uint32_t fjutek;
SemaphoreHandle_t xSemaphore = NULL;
SemaphoreHandle_t xMutex = NULL;
TaskHandle_t xLed1;
TaskHandle_t xLed2;
xQueueHandle kolejka_h;

static void prvSetupHardware(void);
void vATaskFunction( void *pvParameters );
void vLedTask1( void *pvParameters );
void vLedTask2( void *pvParameters );

void vApplicationTickHook( void );


int main(void)
{
  int i = 0;

	// Hardware configuration
	prvSetupHardware();

	kolejka_h = xQueueCreate(1, sizeof(uint8_t));
	if( kolejka_h == NULL ) while(1);

	xTaskCreate( vLedTask1, "LEDTask1", 100, NULL, 1, &xLed1 );
	xTaskCreate( vLedTask2, "LEDTask2", 100, NULL, 2, &xLed2 );

	// Start the scheduler
	vTaskStartScheduler(); // should never return

  /* Infinite loop */
  while (1)
  {
	i++;
  }
}



static void prvSetupHardware(void)
{
	LedGreen.mode 	= output;
	LedGreen.pin 	= LedGreen_pin;
	LedGreen.port 	= LedGreen_port;
	LedGreen.pull	= pullDown;
	LedGreen.typ	= pushPull;
	gpioCfg(&LedGreen);

	DiodeRed.mode     = output;
	DiodeRed.pin      = DiodeRed_pin;
	DiodeRed.port     = DiodeRed_port;
	DiodeRed.pull     = pullDown;
	DiodeRed.typ      = pushPull;
	DiodeRed.speed    = medium;
	gpioCfg(&DiodeRed);

	Button.mode     = input;
	Button.pin      = Button_pin;
	Button.port     = Button_port;
	Button.pull     = pullDown;
	Button.typ      = pushPull;
	Button.speed    = medium;
	gpioCfg(&Button);



}

//pobiera wartosc buttona
void vLedTask1( void *pvParameters )
{
	uint8_t stan_new = 0;
	uint8_t stan_last = 0;
    for( ;; )
    {
    	eTaskState led2;
    	led2 = eTaskGetState(xLed2);

    	stan_new = gpioGetPinState(Button_port, Button_pin);
    	if(stan_last != stan_new)
    	{
        	xQueueSend(kolejka_h, &stan_new, 0);
    	}
    	stan_last = stan_new;
    	//vTaskDelay(200);
    }
    vTaskDelete( NULL );
}


void vLedTask2( void *pvParameters )
{
	uint8_t setOrNot = 0;
    for( ;; )
    {
    	eTaskState led1;

    	led1 = eTaskGetState(xLed1);
    	if(xQueueReceive(kolejka_h,&setOrNot, 100))
    	{
    		if(setOrNot == 1)
    		{
    			gpioPinSetState(LedGreen_port, LedGreen_pin, 1);
    		}
    		else if(setOrNot == 0)
    		{
    			gpioPinSetState(LedGreen_port, LedGreen_pin, 0);
    		}
    	}
    }
    vTaskDelete( NULL );
}

void vApplicationTickHook( void )
{
	fjutek++;


	if(fjutek == (32000))
	{
		fjutek =0;
	}
}
